name: docfx

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docfx:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3

    - name: Install and run docfx
      run: |
        dotnet --info
        dotnet tool restore
        dotnet tool list
        dotnet tool restore
        dotnet tool list
        dotnet tool run docfx --version
